### ISSUE TITLE
暗色皮肤下markdown的引用部分不易辨认

### ISSUE THREAD

**Issue by karlshuyuan** [miluluyo/cute-cnblogs#13]
![](https://i.loli.net/2021/04/06/OhHgTNUV6lui25p.png)
markdown中以`> `开头的行是灰色 , 背景也是偏灰色的 .

**Comment by miluluyo** [comment]
我竟然没发现这个hhhh，这个可以在 darkly.css 中 添加样式，后期我在改一下css文件
```css
.blogpost-body blockquote{color:#606975}
```
